### ISSUE TITLE
unable to get this to work, any help is appreciated.

### ISSUE THREAD

**Issue by ghost** [marclave/Jasper-Twitter#3]
Traceback (most recent call last):
  File "jasper.py", line 12, in <module>
    from client import tts, stt, jasperpath, diagnose
  File "/home/pi/jasper/client/**init**.py", line 1, in <module>
    from modules import Twitter
ImportError: cannot import name Twitter

**Comment by ghost** [comment]
Ok, figured out that problem. Disregard, had the wrong **init, but I just get this:
Traceback (most recent call last):
  File "jasper.py", line 13, in <module>
    from client.conversation import Conversation
  File "/home/pi/jasper/client/conversation.py", line 3, in <module>
    from notifier import Notifier
  File "/home/pi/jasper/client/notifier.py", line 4, in <module>
    from modules import Gmail
  File "/home/pi/jasper/client/modules/__init**.py", line 2, in <module>
    from modules import Twitter
ImportError: No module named modules

**Comment by DerfOh** [comment]
I had a similar error, it was because I had not installed the tweepy dependency. I ran into further trouble with it throwing some error about not being able to be imported but I found [this](http://stackoverflow.com/questions/27465695/cannot-install-tweepy-on-rasbian-with-sudo-pip-install) SO post which solved my issue.

Hope this helps.
